name: Build and deploy ASP.NET Core app to Azure Web App - practicefridge

on:
  push:
    branches: [main]
  workflow_dispatch:

# 统一放一些变量，修改更方便
env:
  DOTNET_VERSION: "8.0.x"
  PROJECT_FILE: fridge-backend/fridge-backend.csproj # ← 如果想用解决方案就改成 Fridge.sln
  PUBLISH_DIR: ${{ github.workspace }}/artifact
  AZURE_WEBAPP_NAME: practicefridge
  AZURE_SLOT_NAME: Production

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_FILE }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_FILE }}" -c Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_FILE }}" -c Release -o "${{ env.PUBLISH_DIR }}" --no-build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write # OIDC 登录需要
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: ./artifact

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          # 这三个 Secrets 是在 Deployment Center/或你手动配置的
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8D46523B0F324A55B90EE872D5910E17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9AB66554D674E8F8BC860C7C6A01ECC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0A879F08B4C24C75B86349D42A439A21 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_SLOT_NAME }} # 如果没有 slot，可删掉这一行
          package: ./artifact
